import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Package, Truck, Users, LogOut } from 'lucide-react';
import { request, setToken, getToken, logout } from './api/client';
import './styles.css';

const states = ['Solicitud','Cotización','Aprobado','Pagado','En tránsito','Aduana','Liberado','Entregado','Cerrado'];
const money = (n) => new Intl.NumberFormat('es-CL', { style:'currency', currency:'CLP', maximumFractionDigits:0 }).format(Number(n || 0));
const blankOp = { name:'', orderNumber:`OMP-${Date.now()}`, requestType:'PEDIDO REALIZADO', status:'Solicitud', supplierName:'', productName:'', quantity:1, hsCode:'', incoterm:'EXW', originCountry:'', deliveryPoint:'', productValue:0, freight:0, insurance:0, localExpenses:0, exchangeRate:1 };

function Login({ onAuth }) { const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'',password:''}); const [err,setErr]=useState('');
 async function submit(e){ e.preventDefault(); setErr(''); try{ const data=await request(`/auth/${mode}`,{method:'POST',body:form}); setToken(data.token); onAuth(data.user);}catch(ex){setErr(ex.message)}}
 return <div className="login"><section className="login-card"><div className="logo">GO</div><h1>Ciao,<br/><b>Benvenuti!</b></h1><form onSubmit={submit}>{mode==='register'&&<input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{err&&<p className="error">{err}</p>}<button>{mode==='login'?'Login':'Crear cuenta'}</button><button type="button" className="secondary" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Sign up':'Volver'}</button></form></section><section className="hero"><div>Gabutti Corse<br/>Import MVP</div></section></div> }
function Shell({children,setPage}){ return <div className="app"><aside><div className="logo small">GO</div><p>MAIN MENU</p><button onClick={()=>setPage('dashboard')}><LayoutDashboard/>Dashboard</button><button onClick={()=>setPage('operations')}><Truck/>Órdenes</button><button onClick={()=>setPage('products')}><Package/>Productos</button><button onClick={()=>setPage('suppliers')}><Users/>Proveedores</button><button onClick={()=>{logout(); location.reload()}}><LogOut/>Salir</button></aside><main>{children}</main></div> }
function Dashboard(){ const [ops,setOps]=useState([]); useEffect(()=>{request('/operations').then(setOps)},[]); const total=ops.reduce((s,o)=>s+(o.totalCostCLP||o.totalCost||0),0); return <><h1>Dashboard</h1><div className="cards"><div className="card"><span>Total operaciones</span><b>{ops.length}</b></div><div className="card"><span>Costo estimado</span><b>{money(total)}</b></div><div className="card"><span>En tránsito/Aduana</span><b>{ops.filter(o=>['En tránsito','Aduana'].includes(o.status)).length}</b></div></div><div className="panel"><h2>Últimas operaciones</h2><Table rows={ops.slice(0,6)} cols={['name','status','incoterm','orderNumber']} /></div></>}
function Table({rows,cols,onEdit,onDelete}){ return <table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}{(onEdit||onDelete)&&<th>Acciones</th>}</tr></thead><tbody>{rows.map(r=><tr key={r._id}>{cols.map(c=><td key={c}>{String(r[c]??'')}</td>)}{(onEdit||onDelete)&&<td><button className="mini" onClick={()=>onEdit(r)}>Editar</button><button className="mini danger" onClick={()=>onDelete(r)}>Eliminar</button></td>}</tr>)}</tbody></table> }
function Operations(){ const [rows,setRows]=useState([]), [form,setForm]=useState(blankOp), [calc,setCalc]=useState(null); const load=()=>request('/operations').then(setRows); useEffect(load,[]); useEffect(()=>{request('/operations/calculate',{method:'POST',body:form}).then(setCalc).catch(()=>{})},[form]); async function save(e){e.preventDefault(); await request(form._id?`/operations/${form._id}`:'/operations',{method:form._id?'PUT':'POST',body:form}); setForm({...blankOp, orderNumber:`OMP-${Date.now()}`}); load();} async function del(r){if(confirm('¿Eliminar?')){await request(`/operations/${r._id}`,{method:'DELETE'});load();}}
 return <><h1>Nueva Orden</h1><form className="grid" onSubmit={save}>{['name','orderNumber','requestType','supplierName','productName','quantity','hsCode','incoterm','originCountry','deliveryPoint','productValue','freight','insurance','localExpenses','exchangeRate'].map(k=><label key={k}>{k}<input value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{states.map(s=><option key={s}>{s}</option>)}</select></label><button>Guardar</button></form>{calc&&<div className="cards"><div className="card"><span>CIF</span><b>{money(calc.cif)}</b></div><div className="card"><span>Ad Valorem 6%</span><b>{money(calc.adValorem)}</b></div><div className="card"><span>IVA 19%</span><b>{money(calc.iva)}</b></div><div className="card"><span>Total</span><b>{money(calc.totalCostCLP || calc.totalCost)}</b></div></div>}<h2>Lista de Órdenes</h2><Table rows={rows} cols={['name','status','supplierName','incoterm','orderNumber']} onEdit={setForm} onDelete={del}/></>}
function CrudPage({title,path,fields}){ const [rows,setRows]=useState([]),[form,setForm]=useState({}); const load=()=>request(path).then(setRows); useEffect(load,[]); async function save(e){e.preventDefault(); await request(form._id?`${path}/${form._id}`:path,{method:form._id?'PUT':'POST',body:form}); setForm({}); load();} async function del(r){if(confirm('¿Eliminar?')){await request(`${path}/${r._id}`,{method:'DELETE'});load();}} return <><h1>{title}</h1><form className="grid" onSubmit={save}>{fields.map(f=><label key={f}>{f}<input value={form[f]??''} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>)}<button>Guardar</button></form><Table rows={rows} cols={fields.slice(0,5)} onEdit={setForm} onDelete={del}/></>}
function App(){ const [auth,setAuth]=useState(!!getToken()),[page,setPage]=useState('dashboard'); if(!auth) return <Login onAuth={()=>setAuth(true)}/>; return <Shell setPage={setPage}>{page==='dashboard'&&<Dashboard/>}{page==='operations'&&<Operations/>}{page==='products'&&<CrudPage title="Productos" path="/products" fields={['code','name','brand','hsCode','price','currency','weight','countryOrigin']}/>} {page==='suppliers'&&<CrudPage title="Proveedores" path="/suppliers" fields={['name','country','contactName','email','phone','notes']}/>}</Shell> }
createRoot(document.getElementById('root')).render(<App/>);
